In [0]:
import numpy as np


In [4]:
my_list = [1,2,3]
my_list


[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
## built in methods

In [11]:
np.arange(0,11,5)

array([ 0,  5, 10])

In [12]:
## Zeros and Ones
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros(((5,5,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
#### Linspace
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [19]:
### EYE
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
## Random
#### rand
np.random.rand(2)

array([0.45932393, 0.04720511])

In [23]:
np.random.rand(5,5)*100

array([[15.42767412,  2.31800658, 19.25793917, 12.75183569, 68.2414039 ],
       [93.56351866, 10.68134299,  3.70680096, 22.90420196, 22.56979892],
       [30.63155815, 13.48185498, 23.21751451, 37.32487342, 26.15759457],
       [36.44487849, 72.89523555, 49.85511246, 90.74412481, 83.3682721 ],
       [60.10131435, 88.8915768 , 45.52467298, 43.19283626, 77.19452658]])

In [24]:
np.random.randint(0,10000,10)

array([7921, 3921,  856, 9772, 1564, 6456, 9323, 2758, 3006, 6289])

In [0]:
## Reshpae
arr = np.arange(25)
randarr = np.random.randint(0,50,10)


In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr.max()

24

In [28]:
arr.argmax()

24

In [29]:
arr.argmin()

0

In [30]:
arr.shape


(25,)

In [32]:
### Numpy indexing and Selection

arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[2:6]

array([2, 3, 4, 5])

In [36]:
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:

arr_2d[:,1]

array([10, 25, 40])

In [44]:
arr_2d[0:2, 1:]

array([[10, 15],
       [25, 30]])

In [46]:
arr_2d[0:2, 1:] = 100
arr_2d


array([[  5, 100, 100],
       [ 20, 100, 100],
       [ 35,  40,  45]])

In [53]:
arr = np.arange(1,100,2)

bool_arr = arr>4

bool_arr

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [54]:

arr[bool_arr]



array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
       73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [55]:
### Numpy operations

arr = np.arange(10)

arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
import numpy as np

In [58]:
a = np.zeros(10)
a


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
b = np.ones(10)
b


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
b*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [63]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [66]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.random.rand(1)

array([0.22339431])

In [73]:
np.random.randn(25)

array([ 0.94921339,  0.37901528, -0.62538638, -1.31448684, -1.0793942 ,
       -1.79887015, -0.85440974, -1.09386735,  0.57181235, -1.28631712,
       -0.06290569,  2.09041706, -0.93453069, -1.41435364,  2.19354184,
       -0.35997629,  0.31884791, -0.5271702 ,  0.41530195, -0.65107296,
        1.8244448 ,  0.44249192,  0.41458952,  0.79539903, -0.46348639])

In [79]:
np.linspace(.01,1.0,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [80]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [81]:
1==1

True

In [84]:
mat = np.arange(1,26).reshape(5,5)

mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [85]:
mat[2: , 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [87]:
mat[3,4]

20

In [94]:
mat[0:3, 1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [95]:
mat[4]

array([21, 22, 23, 24, 25])

In [97]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [98]:
np.sum(mat)

325

In [99]:
np.std(mat)

7.211102550927978

In [100]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

In [101]:
np.sum(mat, axis=1)

array([ 15,  40,  65,  90, 115])